### PR TITLE
Fix provider imports

### LINKED ISSUE #183: Sandboxes are broken
I noticed the sandbox don't run anymore, we might need to bisect when do they break, because If we go some commits back they work.

### PR DESCRIPTION
**Pull request by Velenir**
Fixes #183 

Issue stems from a discrepancy between type declarations and actual exports in `web3-core`

### CODE REVIEW

File: src/helpers/web3.ts [hunk 1]
```diff
@@ -1,6 +1,8 @@
 import assert from 'assert'
 import Web3 from 'web3'
-import { HttpProvider, WebsocketProvider } from 'web3-core'
+// TODO: check if latest version fixes
```
Comment (anxolin) [inline src/helpers/web3.ts:3]: @Velenir can you add a recurring calendar event and maybe an issue to do this check so we don't forget

**Review by anxolin — APPROVED** [review]
Worked perfectly!

**Review by W3stside — APPROVED** [review]
